# Generated by Django 4.2.5 on 2023-09-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='user_role',
        ),
        migrations.AddField(
            model_name='home',
            name='options',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Admin', 'Admin')], default='Admin', max_length=10),
        ),
    ]
